config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('jop.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^', include('jop.posts.urls', namespace='posts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

jop/posts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.post_list,
        name='list'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<slug>\d+)/$',
        view=views.post_detail,
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^new/$',
        view=views.new_post,
        name='new'
    ),

    url(
        regex=r'^add/comment/post/(?P<slug>\d+)/$',
        view=views.new_meme,
        name='new_meme'
    ),

    url(
        regex=r'^vote/up/meme/(?P<slug>\d+)/$',
        view=views.vote_up_meme,
        name='meme_voteup'
    ),
]

jop/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

jop/posts/models.py
import random
import string
import urllib
from django.conf import settings
from django.core.files import File
from django.db import models
from taggit.managers import TaggableManager
import os
from django.utils.translation import ugettext_lazy as _


class Post(models.Model):
    slug = models.SlugField(editable=False, db_index=True, unique=True)
    description = models.TextField(verbose_name=_('Description'), max_length=1000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    cached_image = models.OneToOneField('CachedImage', null=True, blank=True)
    tags = TaggableManager()
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)
    num_votes = models.IntegerField(default=0)
    best_meme = models.ForeignKey('Meme', related_name='memeposts', null=True)
    current_best_votes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        while not self.slug:
            newslug = ''.join(random.choice(string.digits) for _ in range(7))

            if not Post.objects.filter(slug=newslug).count():
                self.slug = newslug

        super(Post, self).save(*args, **kwargs)


class CachedImage(models.Model):
    image_url = models.URLField()
    image_file = models.ImageField(upload_to='images', blank=True)

    def save(self, *args, **kwargs):
        self.cache()
        super(CachedImage, self).save(*args, **kwargs)

    def cache(self):
        """Store image locally if we have a URL"""
        if self.image_url and not self.image_file:
            result = urllib.urlretrieve(self.image_url)
            name = os.path.basename(self.image_url)
            __, ext = os.path.splitext(name)
            newname = ''.join(random.choice(string.digits + string.ascii_letters) for _ in range(10)) + ext
            self.image_file.save(
                newname,
                File(open(result[0]))
            )


class Meme(models.Model):
    slug = models.SlugField(editable=False, db_index=True, unique=True)
    meme = models.TextField(verbose_name=_('Meme'), max_length=100, db_index=True)
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now_add=True)
    num_votes = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        while not self.slug:
            newslug = ''.join(random.choice(string.digits) for _ in range(10))

            if not Meme.objects.filter(slug=newslug).count():
                self.slug = newslug

        super(Meme, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.meme

jop/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

jop/posts/forms.py
from django import forms
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class PostForm(forms.Form):
    title = forms.CharField(label=_('title'), help_text = _('an interesting title'))
    image_url = forms.URLField(label=_('Image URL'), help_text=_('The image URL'))
    tags = forms.CharField(label=_('Tags'), help_text=_('Tags, split by comma'))


class MemeForm(forms.Form):
    meme = forms.CharField(label=_('Meme'), help_text=_('write your meme here'))

jop/posts/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from jop.posts.forms import PostForm, MemeForm
from jop.posts.models import Post, CachedImage, Meme
from django.views.decorators.csrf import csrf_exempt
from voting.models import Vote


def post_list(request):
    posts = Post.objects.all()

    return render_to_response(
        'posts/post_list.html',
        {
            'posts': posts
        },
        context_instance=RequestContext(request))


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = MemeForm()

    return render_to_response(
        'posts/post_detail.html',
        {
            'post': post,
            'form': form
        },
        context_instance=RequestContext(request))


@login_required
def new_post(request):
    post_form = PostForm(request.POST if 'submit' in request.POST else None)

    if request.method == 'POST':
        if post_form.is_valid():
            cd = post_form.cleaned_data
            cached_image = CachedImage()
            cached_image.image_url = cd['image_url']
            cached_image.save()

            post = Post()
            post.cached_image = cached_image
            post.update_date = datetime.now()
            post.author = request.user
            post.save()
            post.tags.add(*cd['tags'].split(','))
            meme = Meme()
            meme.meme = cd['title']
            meme.update_date = datetime.now()
            meme.author = request.user
            meme.post = post
            meme.save()

            post.best_meme = meme
            post.save()

            return HttpResponseRedirect(
                reverse("posts:detail", kwargs={'slug': post.slug}))

    return render_to_response(
        'posts/post_new.html',
        {
            'post_form': post_form
        },
        context_instance=RequestContext(request))


@login_required
def new_meme(request, slug):
    meme_form = MemeForm(request.POST if 'submit' in request.POST else None)

    if request.method == 'POST':
        if meme_form.is_valid():
            cd = meme_form.cleaned_data
            post = get_object_or_404(Post, slug=slug)
            meme = Meme()
            meme.meme = cd['meme']
            meme.update_date = datetime.now()
            meme.author = request.user
            meme.post = post
            meme.save()

            return HttpResponseRedirect(
                reverse("posts:detail", kwargs={'slug': post.slug}))

    raise Http404


@login_required
@csrf_exempt
def vote_up_meme(request, slug):
    template_name = 'posts/includes/meme_footer.html'

    if not request.method == 'POST':
        raise Http404

    meme = get_object_or_404(Meme, slug=slug)
    vote = Vote.objects.get_for_user(meme, request.user)

    if vote:
        Vote.objects.record_vote(meme, request.user, 0)
        meme.num_votes -= 1
        meme.post.num_votes -= 1
    else:
        Vote.objects.record_vote(meme, request.user, 1)
        meme.num_votes += 1
        meme.post.num_votes += 1
        if meme.num_votes > meme.post.current_best_votes:
            meme.post.current_best_votes += 1
            meme.post.best_meme = meme

    meme.save()
    meme.post.save()

    return render_to_response(
        template_name,
        {'meme': meme},
        context_instance=RequestContext(request))

jop/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

jop/templates/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}jop{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 3 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-light navbar-static-top bg-white">
        <div class="container">
          <a class="navbar-brand" href="/">HippoMeme</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'posts:list' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
          <div class="row">
              <div class="col-sm-8">
                  {% block left-pane %}
                  {% endblock %}
              </div>
              <div class="col-sm-4">
                  {% block right-pane %}
                  {% endblock %}
              </div>
          </div>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 3 -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
          <script src="{% static 'js/csrf.js' %}"></script>
          <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 